---
- name: xubuntu
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: enable auto login
    copy:
      dest: "/etc/lightdm/lightdm.conf.d/auto_login.conf"
      content: |
        [SeatDefaults]
        autologin-user={{ ansible_user }}
    become: yes

  - name: restart lightdm
    service:
      name: lightdm
      state: restarted
    become: yes

  - name: remove packages
    apt:
      name: "{{ packages }}"
      state: absent
      autoremove: yes
      purge: yes
    vars:
      packages:
      - gnome-mines
      - gnome-sudoku
      - thunderbird
      - libreoffice*
      - transmission*
      - pidgin*
      - xfce4-notes*
      - sgt*
      - parole
      - xfburn
      - catfish
      - atril
      - xfce4-dict
      - simple-scan
      - ristretto
      - mugshot
      - gimp*
      - gigolo*
    ignore_errors: yes
    become: yes

  - name: install tools
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - tig
      - vim
      - htop
      - ncdu
    become: yes

  - name: use minimal settings
    shell: |
      xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVGA-1/workspace0/image-style -s "0"
      xfconf-query -c xfce4-desktop -p /desktop-icons/style -s 0
      xfconf-query -c xfce4-panel -p /panels/panel-0/autohide-behavior -s 2
      xfconf-query -c xfwm4 -p /general/theme -s "Numix"
      xfconf-query -c xfwm4 -p /general/use_compositing -s "false"

  - name: set user no sudo password
    lineinfile:
      dest: /etc/sudoers
      state: present
      line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes

  - name: disable boot splash
    lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT.*$'
      line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
    become: yes

  - name: update grub
    command: update-grub
    become: yes
